/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author olver
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        btn_colegio = new javax.swing.JButton();
        btn_estudiante = new javax.swing.JButton();
        btn_hstAcademico = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_salud = new javax.swing.JButton();
        btn_origen = new javax.swing.JButton();
        btn_acudiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setPreferredSize(new java.awt.Dimension(381, 30));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SISTEMA DE GESTIÓN ESCOLAR");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        btn_colegio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_colegio.setText("Colegio");
        btn_colegio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_colegio.setPreferredSize(jPanel2.getPreferredSize());
        btn_colegio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_colegioActionPerformed(evt);
            }
        });
        jPanel2.add(btn_colegio);

        btn_estudiante.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_estudiante.setText("Estudiante");
        btn_estudiante.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudianteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_estudiante);

        btn_hstAcademico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_hstAcademico.setText("Historia \nacademica");
        btn_hstAcademico.setToolTipText("");
        btn_hstAcademico.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_hstAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hstAcademicoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hstAcademico);

        jSplitPane2.setLeftComponent(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));

        btn_salud.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_salud.setText("Informe de salud");
        btn_salud.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_salud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saludActionPerformed(evt);
            }
        });
        jPanel3.add(btn_salud);

        btn_origen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_origen.setText("Origen");
        btn_origen.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_origen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_origenActionPerformed(evt);
            }
        });
        jPanel3.add(btn_origen);

        btn_acudiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_acudiente.setText("Acudiente");
        btn_acudiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn_acudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_acudienteActionPerformed(evt);
            }
        });
        jPanel3.add(btn_acudiente);

        jSplitPane2.setRightComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane2);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_colegioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_colegioActionPerformed
        new VistaGestionColegio().setVisible(true);
    }//GEN-LAST:event_btn_colegioActionPerformed

    private void btn_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudianteActionPerformed
        new VistaGestion().setVisible(true);
    }//GEN-LAST:event_btn_estudianteActionPerformed

    private void btn_hstAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hstAcademicoActionPerformed
        try {
            new VistaGestionHistoriaAcademica().setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(VistaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_hstAcademicoActionPerformed

    private void btn_saludActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saludActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_saludActionPerformed

    private void btn_acudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_acudienteActionPerformed
        new VistaGestionAcudiente().setVisible(false);
    }//GEN-LAST:event_btn_acudienteActionPerformed

    private void btn_origenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_origenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_origenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acudiente;
    private javax.swing.JButton btn_colegio;
    private javax.swing.JButton btn_estudiante;
    private javax.swing.JButton btn_hstAcademico;
    private javax.swing.JButton btn_origen;
    private javax.swing.JButton btn_salud;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    // End of variables declaration//GEN-END:variables
}
